### ISSUE TITLE
Merged file's body is empty.

### ISSUE THREAD

**Issue by TheRealPingWin** [marcioggs/ng-i18n-merge-files#10]
I followed the example structure, I have a home component (src/app/home), which contains the components files and the xlf file (home.messages.es.xlf).
After running  npx ng-i18n-merge-files -f xlf I get a messages.es.xlf file in src/locale, but the file's body is empty.

Here's both files:

home.messages.es.xlf

```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="en-US" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="2821179408673282599" datatype="html">
        <source>Home</source>
        <target>Es translation</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/home/home.html</context>
          <context context-type="linenumber">2</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```

messages.es.xlf

```
<?xml version="1.0" encoding="UTF-8"?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="es" datatype="plaintext" original="ng2.template">
    <body/>
  </file>
</xliff>
```

**Comment by marcioggs** [comment]
To avoid you having to repeat the `xliff` and `file` tags on the different files, and also to avoid having to deal with language inconsistency between the one declared on the file content and on the filename, this tool expects you to provide the `body` as the root tag.

Changing home.messages.es.xlf to this format should fix it:
```
<?xml version="1.0" encoding="UTF-8" ?>
<body xmlns="urn:oasis:names:tc:xliff:document:1.2">
      <trans-unit id="2821179408673282599" datatype="html">
        <source>Home</source>
        <target>Es translation</target>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/home/home.html</context>
          <context context-type="linenumber">2</context>
        </context-group>
      </trans-unit>
</body>
```

See https://github.com/marcioggs/ng-i18n-merge-files#xliff-12

Please let me know in case it persists.

**Comment by TheRealPingWin** [comment]
Thanks for the help, it works.
